name: Build Container Images

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
        default: false


permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Image meta
          id: ddg_meta
          uses: docker/metadata-action@v4
          with:
            images: |
              gefyra/docker-desktop-extension
            flavor: |
              latest=false
            tags: |
              type=raw,value=development,enable=${{ inputs.release == false }}
              type=raw,value={{tag}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
        - name: Write variable to Github Action Envrionment
          run: echo "GEFYRA_EXT_RELEASE=$(cat package.json | jq -r '.dependencies.gefyra' | cut -c2-)" >> $GITHUB_ENV
          working-directory: ui
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            build-args: |
              GEFYRA_EXT_RELEASE=${{ env.GEFYRA_EXT_RELEASE }}
            platforms: linux/amd64,linux/arm64
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.ddg_meta.outputs.tags }}
