name: Lint
on:
  push:
    branches:
        - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        - name: Load cached node_modules
          id: cached-node-modules
          uses: actions/cache@v3
          with:
            path: ./ui/node_modules/
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./ui/package-lock.json') }}
        - name: Install deps
          working-directory: ./ui
          run: npm install
          if: steps.cached-node-modules.outputs.cache-hit != 'true'
        - name: Lint UI
          working-directory: ./ui
          run: npm run lint
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Validate metadata.json
          run: docker extension validate metadata.json

          