name: Release & Publish on Docker Hub
on: 
  workflow_dispatch:
    inputs:
        release_type:
            type: choice
            description: Type of release
            options: 
            - patch
            - minor

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                cache-dependency-path: './ui'
            - name: Install the dependencies
              working-directory: ./ui
              run: npm ci
            - name: Initialize Git user
              run: |
                git config --global user.email "robert@blueshoe.io"
                git config --global user.name "Github Action"
            - name: Run release
              working-directory: ./ui
              run: npm run release ${{ github.event.inputs.release_type }}
